apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xiaolusys-celery-gevent
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "xiaolusys-celery-gevent"
  template:
    metadata:
      labels:
        app: xiaolusys-celery-gevent
    spec:
      nodeSelector:
        node: "true"
      imagePullSecrets:
        - name: aliyunrepo
      initContainers:
        - name: fonts
          image: "registry.aliyuncs.com/xiaolu-img/xiaolusys-fonts:latest"
          command: ["sh", "-c", "cp /fonts/* /data/"]
          volumeMounts:
          - name: fonts
            mountPath: /data
      containers:
        - name: celery
          image: "registry.aliyuncs.com/xiaolu-img/xiaolusys:COMMIT_ID"
          imagePullPolicy: Always
          env:
            - name: C_FORCE_ROOT
              value: "1"
            - name: TARGET
              value: k8s-production
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: xiaolusys
                  key: REDIS_AUTH
            - name: MYSQL_AUTH
              valueFrom:
                secretKeyRef:
                  name: xiaolusys
                  key: MYSQL_AUTH
          command: ["celery", "worker", "-A", "shopmanager", "-P", "gevent" , "-c", "200", "--loglevel=INFO", "--time-limit=1800","-Q","xiaolupay,logistics,qrcode,weixin,notify,peroid"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "1024Mi"
          volumeMounts:
          - name: fonts
            mountPath: /data/fonts
          - name: certs
            mountPath: /data/certs
      volumes:
        - name: fonts
          emptyDir: {}
        - name: certs
          secret:
            secretName: certs
