apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xiaolusys
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "xiaolusys"
  template:
    metadata:
      labels:
        app: xiaolusys
    spec:
      nodeSelector:
        node: "true"
      imagePullSecrets:
        - name: aliyunrepo
      containers:
        - name: gunicorn
          image: "registry.aliyuncs.com/xiaolu-img/xiaolusys:COMMIT_ID"
          imagePullPolicy: Always
          env:
            - name: INSTANCE
              value: mall
            - name: TARGET
              value: TARGET_NAME
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: xiaolusys
                  key: REDIS_AUTH
            - name: MYSQL_AUTH
              valueFrom:
                secretKeyRef:
                  name: xiaolusys
                  key: MYSQL_AUTH
          ports:
            - containerPort: 9000
              name: http
          command: ["gunicorn", "-k", "gevent", "-w", "1", "-c", "gunicorn_config.py", "shopmanager.wsgi"]
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1500m"
              memory: "1024Mi"
          volumeMounts:
          - name: certs
            mountPath: /data/certs
      volumes:
        - name: certs
          secret:
            secretName: certs
