apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  name: xiaolusys
  namespace: production
spec:
  ports:
  - name: http
    nodePort: 32592
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: xiaolusys
  sessionAffinity: None
  type: NodePort